### PR TITLE
Fix build on OS X

### PR DESCRIPTION
**Pull request by bgamari**
This was triggered on Darwin.

### CODE REVIEW

**Comment by bgamari** [comment]
IMHO it might be worth using`-fno-warn-unused-imports` here and dropping the CPP from the import lists; this is currently much more fragile than necessary for relatively little benefit.

**Comment by Rufflewind** [comment]
I think it should probably be like this?

    (fromMaybe (utcTimeToPOSIXSeconds atimeOld) atime')
    (fromMaybe (utcTimeToPOSIXSeconds mtimeOld) mtime')

**Comment by bgamari** [comment]
Yes, I just finished iterating this; it now seems to build. I'll squash the two commits and write a better commit message.

**Comment by bgamari** [comment]
@Rufflewind how does this look?

**Comment by bgamari** [comment]
This has been successfully built on Darwin.

**Comment by Rufflewind** [comment]
Thanks.  I might consider adding the warning suppression you suggested.  Probably also a good idea to set up OS X testing on Travis in the future.

**Pull request merged**
