### PR TITLE
Change bounds of filepath dependency

### PR DESCRIPTION
**Pull request by BinderDavid**
Change bounds from <1.4.200 || >= 1.5 to <1.4.300 || >= 1.5

### CODE REVIEW

**Comment by BinderDavid** [comment]
I tried to bump directory in GHC, but GHC uses `filepath=1.4.200.1` which is currently excluded in the bounds of `directory`.

MR in Gitlab is here: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11957

**Comment by Bodigrim** [comment]
Why not bump `filepath` submodule to 1.5 instead? This is long overdue.

**Comment by BinderDavid** [comment]
> Why not bump filepath submodule to 1.5 instead? This is long overdue.

I was hoping that I could get away with just a smaller minor version bump. (Originally it all started because I want to get https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11679 to be able to get merged). But it seems to me that bumping filepath to a new major version is the most sensible way forward. But it will involve bumping several dependencies in GHC at once (at least filepath, directory and Win32).

**Comment by Rufflewind** [comment]
> Change bounds from <1.4.200 || >= 1.5 to <1.4.300 || >= 1.5

FWIW, this was causing deprecation alerts:

> Module ‘System.OsString.Internal.Types’ is deprecated:

and that's why 1.4.200 wasn't marked as supported.

**Comment by BinderDavid** [comment]
Yes, I noticed this now. I think this PR won't be necessary if GHC goes forward with migrating to filepath 1.5.

**Pull request closed without merging**
