### PR TITLE
Fix laziness issue in findExecutable and findFile, add findFileWith

### PR DESCRIPTION
**Pull request by sjakobi**
Fixes https://github.com/haskell/directory/issues/43

### CODE REVIEW

**Comment by Rufflewind** [comment]
Perhaps, instead of using a flag to control the laziness, one could write a lookup function for a single directory (`findFileWithIn`):

~~~hs
findFilesWithIn :: (FilePath -> IO Bool) -> String -> FilePath -> IO (Maybe FilePath)
findFilesWithIn f name d = do
    let path = d </> name
    exist <- doesFileExist path
    if exist
      then do
        ok <- f path
        if ok
          then return (Just path)
          else return Nothing
      else return Nothing
~~~

and then use combinators to construct `findFilesWith` and `findFileWith`:

~~~hs
findFilesWith f ds name = catMaybes <$> traverse (findFilesWithIn f name) ds
findFileWith f ds name = asumMaybeT (findFilesWithIn f name <$> ds)
~~~

The combinator `asumMaybeT` would be written as:

~~~hs
asumMaybeT :: (Foldable t, Monad m) => t (m (Maybe a)) -> m (Maybe a)
asumMaybeT = foldr attempt (return Nothing)
  where attempt mmx mx' = do
          mx <- mmx
          case mx of
            Nothing -> mx'
            Just _  -> return mx
~~~

which is essentially `asum` for `MaybeT`.

**Comment by sjakobi** [comment]
A very elegant solution! I have adjusted my commit accordingly with minor deviations.

**Comment by Rufflewind** [comment]
[To make this work on Windows:](https://ci.appveyor.com/project/Rufflewind/directory-3qidl/build/15-appveyor#L160)

- `getPath` must be wrapped in `#ifndef mingw32_HOST_OS`.
- The test needs to accommodate backslashes instead of slashes.

**Comment by sjakobi** [comment]
> To make this work on Windows:
> 
> getPath must be wrapped in #ifndef mingw32_HOST_OS.
> The test needs to accommodate backslashes instead of slashes.

Of course! Done!

**Comment by Rufflewind** [comment]
Looks good, thanks a lot!

**Comment by sjakobi** [comment]
> Looks good, thanks a lot!

Thanks for the help and especially `asumMaybeT`! I learned something new here!

**Pull request merged**
