### PR TITLE
Support filepath >= 1.5.0.0 and os-string, fixes #164

### LINKED ISSUE #164: Support filepath >= 1.5.0.0 and os-string
See https://github.com/haskell/unix/pull/305

### PR DESCRIPTION
**Pull request by hasufell**
Depends on:

* https://github.com/haskell/unix/pull/305
* https://github.com/haskell/win32/pull/226

### CODE REVIEW

**Comment by hasufell** [comment]
We hope to get this merged in time for GHC 9.10.

**Comment by Rufflewind** [comment]
Thanks for the PR!

**Comment by hasufell** [comment]
Can we get a point release for this?

**Comment by Rufflewind** [comment]
Here you go: https://hackage.haskell.org/package/directory-1.3.8.2

**Pull request merged**
