### PR TITLE
GHCJS patches.

### PR DESCRIPTION
**Pull request by alexanderkjeldaas**
Patches from the GHCJS project.

### CODE REVIEW

**Comment by Rufflewind** [comment]
Hi, thanks for the pull request!

Since this is a very significant patch, it might take some time to go over everything.  For now, here's the major issues I see:

  * Existing Travis CI tests are failing.  It appears Cabal does not recognize `ghcjs` as a valid compiler, or at least the older versions seem to  complain about it.  Can this be worked around somehow?
  * In order to support GHCJS as a first-class platform over the long-term, automated testing is necessary.  Could GHCJS be configured run on Travis CI?

**Comment by Rufflewind** [comment]
I rebased your changes against the latest master: https://github.com/Rufflewind/directory/tree/alexanderkjeldaas-ghcjs-patches

Please verify if the patch still works on GHCJS.  Also, consider [making use of the Internal.Prelude module in Internal.GHCJS](https://github.com/haskell/directory/pull/82#discussion_r189457808), where possible.  Thanks!

**Comment by Rufflewind** [comment]
Closing due to inactivity.  If anyone is interested in continuing this work, here's the *rebased* patch (against the current master 19d6dc0d33366a8920bf8acc7a0fd3ef533d39c3):

```diff
From 94f14f62970b9992e53f3eb44cf502354eccb641 Mon Sep 17 00:00:00 2001
From: Alexander Kjeldaas <ak@astor.ai>
Date: Sun, 13 May 2018 21:33:25 +0200
Subject: [PATCH] GHCJS patches.

---
 System/Directory/Internal.hs        |   8 +-
 System/Directory/Internal/Config.hs |   3 +
 System/Directory/Internal/GHCJS.hs  | 387 ++++++++++++++++++++++++++++
 directory.cabal                     |   4 +
 tools/testscript                    |   5 +-
 5 files changed, 404 insertions(+), 3 deletions(-)
 create mode 100644 System/Directory/Internal/GHCJS.hs

diff --git a/System/Directory/Internal.hs b/System/Directory/Internal.hs
index 31659a5b..b155ae9a 100644
--- a/System/Directory/Internal.hs
+++ b/System/Directory/Internal.hs
@@ -13,7 +13,9 @@
 module System.Directory.Internal
   ( module System.Directory.Internal.Common
 
-#if defined(mingw32_HOST_OS)
+#if defined(ghcjs_HOST_OS)
+  , module System.Directory.Internal.GHCJS
+#elif defined(mingw32_HOST_OS)
   , module System.Directory.Internal.Windows
 #else
   , module System.Directory.Internal.Posix
@@ -23,7 +25,9 @@ module System.Directory.Internal
 
 import System.Directory.Internal.Common
 
-#if defined(mingw32_HOST_OS)
+#if defined(ghcjs_HOST_OS)
+import System.Directory.Internal.GHCJS
+#elif defined(mingw32_HOST_OS)
 import System.Directory.Internal.Windows
 #else
 import System.Directory.Internal.Posix
diff --git a/System/Directory/Internal/Config.hs b/System/Directory/Internal/Config.hs
index 3029f040..733e78c4 100644
--- a/System/Directory/Internal/Config.hs
+++ b/System/Directory/Internal/Config.hs
@@ -1,5 +1,6 @@
 {-# LANGUAGE CPP #-}
 module System.Directory.Internal.Config where
+#if !defined(ghcjs_HOST_OS)
 #include <HsDirectoryConfig.h>
 
 exeExtension :: String
@@ -8,3 +9,5 @@ exeExtension = EXE_EXTENSION
 -- builds, so we use this ugly workaround where we simply paste the C string
 -- literal directly in here.  This will probably break if the EXE_EXTENSION
 -- contains strange characters, but hopefully no sane OS would ever do that.
+
+#endif
diff --git a/System/Directory/Internal/GHCJS.hs b/System/Directory/Internal/GHCJS.hs
new file mode 100644
index 00000000..1f10a70d
--- /dev/null
+++ b/System/Directory/Internal/GHCJS.hs
@@ -0,0 +1,387 @@
+{-# LANGUAGE CPP #-}
+#if defined(ghcjs_HOST_OS)
+{-# LANGUAGE JavaScriptFFI #-}
+#endif
+module System.Directory.Internal.GHCJS where
+#if defined(ghcjs_HOST_OS)
+import System.Directory.Internal.Common
+
+import Data.Bits
+import Data.Maybe (listToMaybe)
+import Data.Time (UTCTime)
+import Data.Time.Clock.POSIX
+  (POSIXTime, posixSecondsToUTCTime, utcTimeToPOSIXSeconds)
+import Foreign.C.Error
+import System.IO.Error
+import GHCJS.Prim
+
+type JSObject = JSVal
+type JSString = JSVal
+type JSArray  = JSVal
+
+throwErrnoIfJSNull :: String -> IO JSVal -> IO JSVal
+throwErrnoIfJSNull msg m = do
+  r <- m
+  if isNull r then throwErrno msg
+              else return r
+
+--------------------------------------------------------------
+
+-- the object is treated as immutable
+newtype Metadata = Metadata JSObject
+
+getSymbolicLinkMetadata :: FilePath -> IO Metadata
+getSymbolicLinkMetadata path =
+  (`ioeSetFileName` path) `modifyIOError` do
+    cpath <- throwErrnoIfJSNull "getSymbolicLinkMetadata" $
+      js_canonicalizePath (toJSString path)
+    mdata <- throwErrnoIfJSNull "getSymbolicLinkMetadata" $
+      js_getFileOrSymlinkStatus cpath
+    pure (Metadata mdata)
+
+getFileMetadata :: FilePath -> IO Metadata
+getFileMetadata path =
+  (`ioeSetFileName` path) `modifyIOError` do
+      cpath <- throwErrnoIfJSNull "getFileMetadata" $
+        js_canonicalizePath (toJSString path)
+      mdata <- throwErrnoIfJSNull "getFileMetadata" $
+        js_getFileStatus cpath
+      pure (Metadata mdata)
+
+linkToDirectoryIsDirectory :: Bool
+linkToDirectoryIsDirectory = False
+
+createSymbolicLink :: Bool -> FilePath -> FilePath -> IO ()
+createSymbolicLink _ target link =
+  throwErrnoIfMinus1_ "createSymbolicLink" $
+    js_createSymbolicLink (toJSString target) (toJSString link)
+
+readSymbolicLink :: FilePath -> IO FilePath
+readSymbolicLink path = do
+  tgt <- throwErrnoIfJSNull "readSymbolicLink" $
+    js_readSymbolicLink (toJSString path)
+  pure (fromJSString tgt)
+
+createDirectoryInternal :: FilePath -> IO ()
+createDirectoryInternal path =
+  (`ioeSetFileName` path) `modifyIOError` do
+    throwErrnoIfMinus1_ "createDirectory" $
+      js_createDirectory (toJSString path)
+
+renamePathInternal :: FilePath -> FilePath -> IO ()
+renamePathInternal opath npath =
+  throwErrnoIfMinus1_ "renamePath" $
+    js_renamePath (toJSString opath) (toJSString npath)
+
+removePathInternal :: FilePath -> IO ()
+removePathInternal True path =
+  throwErrnoIfMinus1_ "removeDirectory" $
+    js_removeDirectory (toJSString path)
+removePathInternal False path =
+  throwErrnoIfMinus1_ "removeFile" $
+    js_removeFile (toJSString path)
+
+canonicalizePathWith :: ((FilePath -> IO FilePath) -> FilePath -> IO FilePath)
+                     -> FilePath
+                     -> IO FilePath
+canonicalizePathWith _ path = do
+  -- fixme implement correct exception behaviour for GHCJS impl
+  cpath <- throwErrnoIfJSNull "canonicalizePath" $
+    js_canonicalizePath (toJSString path)
+  pure (fromJSString cpath)
+
+findExecutablesLazyInternal :: FilePath -> ListT IO [FilePath]
+findExecutablesLazyInternal binary = liftJoinListT $ do
+  arr <- throwErrnoIfJSNull "findExecutables" $
+    js_findExecutables (toJSString binary)
+  (listToListT . (fromJSString <$>)) <$> (fromJSArray arr)
+
+exeExtension = fromJSString js_exeExtension
+
+getDirectoryContentsInternal :: FilePath -> IO [FilePath]
+getDirectoryContentsInternal path = do
+  arr <- throwErrnoIfJSNull "getDirectoryContents" $
+    js_getDirectoryContents (toJSString path)
+  (fromJSString <$>) <$> fromJSArray arr
+
+getCurrentDirectoryInternal :: IO FilePath
+getCurrentDirectoryInternal =
+  fromJSString <$> throwErrnoIfJSNull "getCurrentDirectory"
+                                      js_getCurrentDirectory
+
+setCurrentDirectoryInternal :: FilePath -> IO ()
+setCurrentDirectoryInternal path =
+  throwErrnoIfMinus1_ "setCurrentDirectory" $
+    js_setCurrentDirectory (toJSString path)
+
+copyFileWithMetadataInternal :: (Metadata -> FilePath -> IO ())
+                             -> (Metadata -> FilePath -> IO ())
+                             -> FilePath
+                             -> FilePath
+                             -> IO ()
+copyFileWithMetadataInternal _ _ src dst =
+  js_copyFileWithMetadata (toJSString src) (toJSString dst)
+
+setTimes :: FilePath -> (Maybe POSIXTime, Maybe POSIXTime) -> IO ()
+setTimes path (atime, mtime) =
+  throwErrnoIfMinus1_ "setFileTimes" $
+    js_setFileTimes (toJSString path) atime' set_atime mtime' set_mtime
+  where
+    f = maybe (0, False) ((\ x -> (x, True)) . realToFrac)
+    (atime', set_atime) = f atime
+    (mtime', set_mtime) = f mtime
+
+fileTypeFromMetadata :: Metadata -> FileType
+fileTypeFromMetadata info
+  | isLink    = if isDir then DirectoryLink else SymbolicLink
+  | isDir     = Directory
+  | otherwise = File
+  where
+    isLink = js_getFileStatusIsSymbolicLink info
+    isDir  = js_getFileStatusIsDirectory info
+
+fileSizeFromMetadata :: Metadata -> Integer
+fileSizeFromMetadata = round . js_getFileStatusFileSize
+
+accessTimeFromMetadata :: Metadata -> UTCTime
+accessTimeFromMetadata =
+  posixSecondsToUTCTime . realToFrac . js_getFileStatusAccessTime
+
+modificationTimeFromMetadata :: Metadata -> UTCTime
+modificationTimeFromMetadata =
+  posixSecondsToUTCTime . realToFrac . js_getFileStatusModificationTime
+
+type Mode = Int
+
+ownerReadMode, groupReadMode, otherReadMode :: Mode
+ownerReadMode = 0o400
+groupReadMode = 0o040
+otherReadMode = 0o004
+
+ownerWriteMode, groupWriteMode, otherWriteMode :: Mode
+ownerWriteMode = 0o200
+groupWriteMode = 0o020
+otherWriteMode = 0o002
+
+ownerExecuteMode, groupExecuteMode, otherExecuteMode :: Mode
+ownerExecuteMode = 0o100
+groupExecuteMode = 0o010
+otherExecuteMode = 0o001
+
+modeFromMetadata :: Metadata -> Mode
+modeFromMetadata = js_getFileStatusFileMode
+
+allWriteMode :: Mode
+allWriteMode =
+  ownerWriteMode .|.
+  groupWriteMode .|.
+  otherWriteMode
+
+hasWriteMode :: Mode -> Bool
+hasWriteMode m = m .&. allWriteMode /= 0
+
+setWriteMode :: Bool -> Mode -> Mode
+setWriteMode False m = m .&. complement allWriteMode
+setWriteMode True  m = m .|. allWriteMode
+
+setFileMode :: FilePath -> Mode -> IO ()
+setFileMode path mode =
+  throwErrnoIfMinus1_ "setFileMode" $
+    js_setFileMode (toJSString path) mode
+
+setFilePermissions :: FilePath -> Mode -> IO ()
+setFilePermissions = setFileMode
+
+fileAccess :: FilePath -> Bool -> Bool -> Bool -> IO Bool
+fileAccess path r_ok w_ok x_ok = fileAccess' (toJSString path) r_ok w_ok x_ok
+
+fileAccess' :: JSString -> Bool -> Bool -> Bool -> IO Bool
+fileAccess' path r_ok w_ok x_ok = js_getFileAccess path r_ok w_ok x_ok
+
+getAccessPermissions :: FilePath -> IO Permissions
+getAccessPermissions path = do
+  m <- getFileMetadata path
+  let isDir = fileTypeIsDirectory (fileTypeFromMetadata m)
+      path' = toJSString path
+  r <- fileAccess' path' True  False False
+  w <- fileAccess' path' False True  False
+  x <- fileAccess' path' False False True
+  return Permissions
+         { readable   = r
+         , writable   = w
+         , executable = x && not isDir
+         , searchable = x && isDir
+         }
+
+setAccessPermissions :: FilePath -> Permissions -> IO ()
+setAccessPermissions path (Permissions r w e s) = do
+  m <- getFileMetadata path
+  setFileMode path (modifyBit (e || s) ownerExecuteMode .
+                    modifyBit w ownerWriteMode .
+                    modifyBit r ownerReadMode .
+                    modeFromMetadata $ m)
+  where
+    modifyBit :: Bool -> Mode -> Mode -> Mode
+    modifyBit False b m = m .&. complement b
+    modifyBit True  b m = m .|. b
+
+getHomeDirectoryInternal :: IO FilePath
+getHomeDirectoryInternal =
+  fromJSString <$> throwErrnoIfJSNull "getHomeDirectory" js_getHomeDirectory
+
+getXdgDirectoryInternal :: IO FilePath -> XdgDirectory -> IO FilePath
+getXdgDirectoryInternal _ _ = "fixme: getXdgDirectory not implemented for GHCJS"
+
+getXdgDirectoryListInternal :: XdgDirectoryList -> IO [FilePath]
+getXdgDirectoryListInternal xdgDir =
+  case xdgDir of
+    XdgDataDirs   -> get "XDG_DATA_DIRS"   ["/usr/local/share/", "/usr/share/"]
+    XdgConfigDirs -> get "XDG_CONFIG_DIRS" ["/etc/xdg"]
+  where
+    get name fallback = do
+      env <- lookupEnv name
+      case env of
+        Nothing    -> pure fallback
+        Just paths -> pure (splitSearchPath paths)
+
+getAppUserDataDirectoryInternal :: FilePath -> IO FilePath
+getAppUserDataDirectoryInternal appName = do
+  fromJSString <$> throwErrnoIfJSNull "getAppUserDataDirectory"
+    (js_getAppUserDataDirectory (toJSString appName))
+
+getUserDocumentsDirectoryInternal :: IO FilePath
+getUserDocumentsDirectoryInternal =
+  fromJSString <$> throwErrnoIfJSNull "getUserDocumentsDirectory"
+    js_getUserDocumentsDirectory
+
+getTemporaryDirectoryInternal :: IO FilePath
+getTemporaryDirectoryInternal =
+  fromJSString <$> throwErrnoIfJSNull "getTemporaryDirectory"
+    js_getTemporaryDirectory
+
+
+foreign import javascript interruptible
+  "h$directory_getPermissions($1,$c);"
+  js_getPermissions :: JSString -> IO Int
+
+foreign import javascript interruptible
+  "h$directory_setPermissions($1,$2,$c);"
+  js_setPermissions :: JSString -> Int -> IO Int
+
+foreign import javascript interruptible
+  "h$directory_copyPermissions($1,$2,$c);"
+  js_copyPermissions :: JSString -> JSString -> IO Int
+
+foreign import javascript interruptible
+  "h$directory_createDirectory($1,$c);"
+  js_createDirectory :: JSString -> IO Int
+
+foreign import javascript interruptible
+  "h$directory_createSymbolicLink($1,$2,$c);"
+  js_createSymbolicLink :: JSString -> JSString -> IO Int
+
+foreign import javascript interruptible
+  "h$directory_removeDirectory($1,$c);"
+  js_removeDirectory :: JSString -> IO Int
+
+foreign import javascript interruptible
+  "h$directory_removeFile($1,$c);"
+  js_removeFile :: JSString -> IO Int
+
+foreign import javascript interruptible
+  "h$directory_renamePath($1,$2,$c);"
+  js_renamePath :: JSString -> JSString -> IO Int
+
+foreign import javascript unsafe
+  "h$directory_canonicalizePath($1)"
+  js_canonicalizePath :: JSString -> IO JSString
+
+foreign import javascript interruptible
+  "h$directory_findExecutables($1,$c);"
+  js_findExecutables :: JSString -> IO JSArray
+
+foreign import javascript unsafe
+  "h$directory_exeExtension()"
+  js_exeExtension :: JSVal
+
+foreign import javascript interruptible
+  "h$directory_getDirectoryContents($1,$c);"
+  js_getDirectoryContents :: JSString -> IO JSArray
+
+foreign import javascript interruptible
+  "h$directory_copyFileWithMetadata($1,$2,$c);"
+  js_copyFileWithMetadata :: JSString -> JSString -> IO ()
+
+foreign import javascript unsafe
+  "h$directory_getCurrentDirectory()"
+  js_getCurrentDirectory :: IO JSString
+
+foreign import javascript unsafe
+  "h$directory_setCurrentDirectory($1)"
+  js_setCurrentDirectory :: JSString -> IO Int
+
+foreign import javascript unsafe
+  "h$directory_getHomeDirectory()"
+  js_getHomeDirectory :: IO JSString
+
+foreign import javascript unsafe
+  "h$directory_getAppUserDataDirectory($1)"
+  js_getAppUserDataDirectory :: JSString -> IO JSString
+
+foreign import javascript unsafe
+  "h$directory_getUserDocumentsDirectory()"
+  js_getUserDocumentsDirectory :: IO JSString
+
+foreign import javascript unsafe
+  "h$directory_getTemporaryDirectory()"
+  js_getTemporaryDirectory :: IO JSString
+
+foreign import javascript interruptible
+  "h$directory_getFileStatus($1,$c);"
+  js_getFileStatus :: JSString -> IO JSVal
+
+foreign import javascript interruptible
+  "h$directory_getFileOrSymlinkStatus($1,$c);"
+  js_getFileOrSymlinkStatus :: JSString -> IO JSVal
+
+foreign import javascript unsafe
+  "h$directory_getFileStatusModificationTime($1)"
+  js_getFileStatusModificationTime :: Metadata -> Double
+
+foreign import javascript unsafe
+  "h$directory_getFileStatusAccessTime($1)"
+  js_getFileStatusAccessTime :: Metadata -> Double
+
+foreign import javascript unsafe
+  "h$directory_getFileStatusIsDirectory($1)"
+  js_getFileStatusIsDirectory :: Metadata -> Bool
+
+foreign import javascript unsafe
+  "h$directory_getFileStatusIsSymbolicLink($1)"
+  js_getFileStatusIsSymbolicLink :: Metadata -> Bool
+
+foreign import javascript unsafe
+  "h$directory_getFileStatusFileMode($1)"
+  js_getFileStatusFileMode :: Metadata -> Int
+
+foreign import javascript unsafe
+  "h$directory_getFileStatusFileSize($1)"
+  js_getFileStatusFileSize :: Metadata -> Double
+
+foreign import javascript interruptible
+  "h$directory_getFileAccess($1,$2,$3,$4,$c);"
+  js_getFileAccess :: JSString -> Bool -> Bool -> Bool -> IO Bool
+
+foreign import javascript interruptible
+  "h$directory_setFileMode($1,$2,$c);"
+  js_setFileMode :: JSString -> Mode -> IO Int
+
+foreign import javascript interruptible
+  "h$directory_readSymbolicLink($1,$c);"
+  js_readSymbolicLink :: JSString -> IO JSString
+
+foreign import javascript interruptible
+  "h$directory_setFileTimes($1,$2,$3,$4,$5,$c);"
+  js_setFileTimes :: JSString -> Double -> Bool -> Double -> Bool -> IO Int
+
+#endif
diff --git a/directory.cabal b/directory.cabal
index cc788fbc..7a8cba12 100644
--- a/directory.cabal
+++ b/directory.cabal
@@ -49,6 +49,7 @@ Library
         System.Directory.Internal.C_utimensat
         System.Directory.Internal.Common
         System.Directory.Internal.Config
+        System.Directory.Internal.GHCJS
         System.Directory.Internal.Posix
         System.Directory.Internal.Windows
 
@@ -58,6 +59,9 @@ Library
         base     >= 4.5 && < 4.13,
         time     >= 1.4 && < 1.10,
         filepath >= 1.3 && < 1.5
+    if impl(ghcjs)
+        other-extensions: JavaScriptFFI
+        build-depends: ghcjs-prim
     if os(windows)
         build-depends: Win32 >= 2.2.2 && < 2.9
     else
diff --git a/tools/testscript b/tools/testscript
index 9ebd41ee..96a29905 100755
--- a/tools/testscript
+++ b/tools/testscript
@@ -127,7 +127,10 @@ build() {
         cabal configure -v2 --enable-tests --ghc-options="$ghcflags"
         cabal build
         cabal test --show-details="$streaming" $testflags
-        cabal check
+        # GHCJS is not supported on older versions of Cabal
+        if [ `tools/vercmp "$CABALVER" 1.22` -ge 0 ]; then
+            cabal check
+        fi
         cabal sdist
         cabal copy
         cabal_install_run_tests dist/*-*.tar.gz --force-reinstalls
```

**Comment by hvr** [comment]
@Rufflewind fyi, re

> Travis CI for GHCJS will be required for this pull request, preferably without causing a substantial increase in the overall execution time.

...that's one of the reasons I've started packaging up GHCJS in https://launchpad.net/~hvr/+archive/ubuntu/ghcjs :-)

**Pull request closed without merging**
