### PR TITLE
Resolve #100. XDG paths have to be absolute

### LINKED ISSUE #100: getXdgDirectory accepts relative path in XDG_CACHE_HOME
https://github.com/haskell/directory/issues/87 was nonsense, as I commented in that issue.

Relative `XDG_CACHE_HOME` just doesn't make any sense, relative **to what**.

https://www.freedesktop.org/wiki/Specifications/basedir-spec/ links to latest, which says

> All paths set in these environment variables must be absolute. If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.

There's even the source: https://github.com/freedesktop/xdg-specs/tree/master/basedir with history,  https://github.com/freedesktop/xdg-specs/commits/master/basedir/basedir-spec.xml

### PR DESCRIPTION
**Pull request by phadej**
Morally revert b9d0d694fdae951961eb3755a2c367b1ae09a25b

### CODE REVIEW

**Comment by bgamari** [comment]
Looks good to me. However, perhaps we should note this revert in the changelog given how much confusion this issue has caused.

**Comment by phadej** [comment]
I'd like to leave the changelog writing and version bumping to the maintainers.

**Comment by phadej** [comment]
amended the pull request

**Comment by phadej** [comment]
I'm not sure about the next version though. Maybe it should be `1.5.0.0`. I did need to change the tests, so I did break something. But I can leave with fact that 1.3.3.2 and 1.3.4.0 were wrong versions and avoid them (if I can)

**Pull request merged**
