### PR TITLE
Update directory.cabal

### PR DESCRIPTION
**Pull request by nicoladimauro**

### CODE REVIEW

**Comment by Rufflewind** [comment]
The `.cabal` file requires `python` as a build-tool, but the flag is supported only via Custom.

**Comment by nicoladimauro** [comment]
Yes, bit cabal install with the custom flag gives an error
ndm
Il 14/mag/2015 16:46 Phil Ruffwind <notifications@github.com> ha scritto:The .cabal file requires python as a build-tool, but the flag is supported only via Custom.

**Comment by Rufflewind** [comment]
What is the error message? What version of Cabal are you using?

**Comment by nicoladimauro** [comment]
with the command "cabal install directory" I got the following error 
without setting the flag to Simple

directory-1.2.2.1 failed during the configure step. The exception was:
user error (The package requires Cabal library version -any && >= 1.10 
but no
suitable version is installed.)

while the command "cabal --version" gives me

cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library

Il 14/05/2015 17:56, Phil Ruffwind ha scritto:
> What is the error message? What version of Cabal are you using?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/haskell/directory/pull/27#issuecomment-102082548

-- 
-oo------------------------------------------------------------
Nicola Di Mauro, Ph.D.             http://www.di.uniba.it/~ndm/
Department of Computer Science - University of Bari "Aldo Moro"
Via Orabona, 4 - 70126 Bari, Italy Phone: +39 080 544 2297
--
Per favore non mandatemi allegati in Word o PowerPoint.
http://www.gnu.org/philosophy/no-word-attachments.html

**Comment by Rufflewind** [comment]
I tried reproducing the issue with the same cabal-install and Cabal versions but without any success (Debian Wheezy + GHC 7.4.1).

What version of GHC and operating system are you using?

**Comment by Rufflewind** [comment]
A few other things to check:

  - Run `ghc-pkg check 2>&1 | grep -v 'Warning: haddock'` and make sure no errors appear.
  - Run `ghc-pkg describe Cabal | grep version` and make sure 1.16.0 is present.
  - See if you can reproduce the issue on with a clean Cabal configuration (e.g. temporarily move `~/.ghc` and `~/.cabal` elsewhere, or create a new user account).

**Comment by Rufflewind** [comment]
Closing as the issue cannot be reproduced.  It also doesn't matter anymore since the tests have been migrated and the build is `Configure` once again.

**Pull request closed without merging**
